name: Auto Rebuild & Push to GHCR on Base Image Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs hourly (you can change this)
  workflow_dispatch:      # Also allow manual trigger

jobs:
  rebuild-if-base-image-updated:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # to push commit with new digest
      packages: write        # to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current base image digest
        id: get_digest
        run: |
          BASE_IMAGE="python:3.11-slim"
          DIGEST=$(docker buildx imagetools inspect $BASE_IMAGE --format '{{json .Manifest.Digest}}' | jq -r .)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Load previous digest (if any)
        id: load_digest
        run: |
          if [ -f .base_image_digest ]; then
            echo "prev_digest=$(cat .base_image_digest)" >> $GITHUB_OUTPUT
          else
            echo "prev_digest=" >> $GITHUB_OUTPUT
          fi

      - name: Check if base image has changed
        id: changed
        run: |
          if [ "${{ steps.get_digest.outputs.digest }}" != "${{ steps.load_digest.outputs.prev_digest }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image to GHCR
        if: steps.changed.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/mrrobot245/radarr:latest

      - name: Save new digest
        if: steps.changed.outputs.changed == 'true'
        run: echo "${{ steps.get_digest.outputs.digest }}" > .base_image_digest

      - name: Commit updated digest file
        if: steps.changed.outputs.changed == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .base_image_digest
          git commit -m "Update base image digest"
          git push
